### ISSUE TITLE
Runtime Environment [jump cannon]

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#3402]
- [x] make host object comparison deep
- [x] write some unit tests
- [x] wasmi - go no/go
   - [x] switch to stellar-specific wasmi fork
   - [x] merge wasmi integrated gas metering
   - [x] upgrade wasmi fork to the v1 API since they've deprecated the old one
- [x] add storage backend for contracts and contract data
- [x] prohibit FP ops or else normalize FP values and FP environment
- [ ] support contract "specs" / schemas / signatures / types
  - [ ] ~~add host object vocabulary to represent types as first class values~~
  - [ ] ~~add host functions for constructing types~~
  - [ ] ~~add host functions for checking value conformance to a type~~
  - [ ] check contract arguments match spec on invocation
  - [ ] check contract spec-compatibility on upgrade
- [x] event/logging subsystem #3487
- [x] record and export host metrics to core
- [x] tracy integration #3433
- [x] support host-crate multi-versioning in core: #3471
- [x] consolidate XDR definitions between C++ and Rust
  - [x] move XDR to submodule: #3470 
  - [x] check XDR consistency between Rust and C++: #3452
- [x] tighten "security" semantics
  - [x] never accept ScStatus values as input or store in objects
  - [x] enforce host-object read encapsulation: https://github.com/stellar/rs-stellar-contract-env/pull/132
  - [x] enforce non-reentry flag for cross-contract calls
- [x] update CAP-46 to reflect recent changes
  - [x] subtransactions and rollback
  - [x] vast expansion of ScStatusType and ScStatus
  - [x] renaming pos_i64 back to u63
  - [x] not-completely-empty section on metering 
  - [x] read encapsulation, non-reentry, scstatus prohibition
  - [x] replace "C++" with "rust" in various places
  - [x] update references to PRs and repos
- [x] #3488
- [x] security review
- [x] #3489 / https://github.com/stellar/rs-stellar-contract-env/issues/160
- [x] performance testing
  - [x] support & annotate tracy tracing in host crate
- [x] fuzzing

**Comment by graydon** [comment]
Done as much as we're going to do (one section skipped).
