### ISSUE TITLE
Metering and limits [jump cannon]

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#3404]
This issue tracks how the runtime will measure resource utilization while executing contracts.

- [x] improve metering infrastructure and cost model https://github.com/stellar/rs-stellar-contract-env/issues/160
- [x] add cost models and charge them in host functions https://github.com/stellar/rs-soroban-env/issues/232
- [x] load cost models from `CONFIG_SETTING` LEs https://github.com/stellar/rs-soroban-env/issues/305
- [x] calibrate cost models https://github.com/stellar/rs-soroban-env/issues/296

**Comment by graydon** [comment]
Done
