### ISSUE TITLE
priority flooding: extensive tests

### ISSUE THREAD

**Issue by marta-lokhova** [stellar/stellar-core#3817]
Follow up to https://github.com/stellar/stellar-core/pull/3766: these changes need to be extensively tested ahead of the testnet launch

```[tasklist]
### Tasks
- [ ] Unit tests: TxSet validation
- [ ] Unit tests: small network generates mixed soroban and classic load; randomize resource declarations, fees etc. Generate enough load to trigger surge pricing
- [ ] Unit tests: throttled flooding
- [ ] Unit tests: tx queue limiter eviction
- [x] End-to-end simulation: spin up a large network with real latencies, test mix of soroban and classic load with surge pricing
```
