### ISSUE TITLE
Evict Persistent Entries

### ISSUE THREAD

**Issue by SirTyson** [stellar/stellar-core#4392]
Implement full State Archival.
```[tasklist]
### Tasks
- [ ] https://github.com/stellar/stellar-core/issues/4393
- [ ] https://github.com/stellar/stellar-core/issues/4394
- [ ] https://github.com/stellar/stellar-core/issues/4395
- [ ] https://github.com/stellar/stellar-core/issues/4396
- [ ] https://github.com/stellar/stellar-core/issues/4397
- [ ] https://github.com/stellar/stellar-core/issues/4398
- [ ] https://github.com/stellar/stellar-core/issues/4399
- [ ] https://github.com/stellar/stellar-core/issues/4493
```
